"""
generate_seed.py
================
Generate a small, believable *synthetic* DogGraph and emit it as Cypher
(`seed_synthetic.cypher`) ready to paste into Neo4j AuraDB.

The graph encodes Barkley's behavioral-intelligence model as relationships:

    Dog ── HAS_BASELINE ──> Baseline
    Dog ── GENERATED ─────> BehaviorEvent ── FALLS_IN ──> TemporalBin
    Dog ── HAS_DRIFT ─────> DriftEvent ── DRIFTED_FROM ──> Baseline
    DriftEvent ── MODULATED_BY ──> ContextEvent
    Dog ── RECOMMENDED_ROUTE ──> Route ── LOCATED_NEAR ──> Location
    Dog ── COMPATIBLE_WITH {score, reason} ──> Dog

Synthetic data only. No real animals. No output is diagnostic.
"""
from __future__ import annotations

import random

SEED = 42
rng = random.Random(SEED)

# Five behavioral channels (CMCI). Cortisol is a separate Phase-2 channel, omitted here.
CHANNELS = ["activity_level", "sleep_fragmentation", "restlessness_index",
            "location_entropy", "social_response_latency"]

# A small cast. Kikoo is our focus dog: drifting, with a recommended route and a match.
DOGS = [
    # id,    name,      breed,                 birth_year, drifting?, drift_rate, modulated_by_context
    ("d_kikoo",  "Kikoo",  "Jack Russell Terrier", 2017, True,  0.62, "low_activity_period"),
    ("d_juno",   "Juno",   "Border Collie",        2016, True,  0.41, None),
    ("d_pixel",  "Pixel",  "Whippet",              2019, False, 0.08, None),
    ("d_marlow", "Marlow", "Labrador Retriever",   2015, True,  0.55, "post_surgery_recovery"),
    ("d_sable",  "Sable",  "Belgian Malinois",     2020, False, 0.12, None),
    ("d_ollie",  "Ollie",  "Cavalier Spaniel",     2018, False, 0.19, None),
]

# Locations and routes (for route recommendation tied to current state).
LOCATIONS = [
    ("loc_riverside", "Riverside Park",   44.92, 0.48),
    ("loc_oakhill",   "Oak Hill Meadow",  44.90, 0.51),
    ("loc_quiet",     "Quiet Lane",       44.93, 0.46),
]
ROUTES = [
    # id,        name,          terrain,  intensity (1 low - 5 high), near_location
    ("r_river",  "River Path",  "flat",   2, "loc_riverside"),
    ("r_ridge",  "Ridge Loop",  "hilly",  4, "loc_oakhill"),
    ("r_quiet",  "Quiet Lane",  "flat",   1, "loc_quiet"),
]

CONTEXT_TYPES = {
    "low_activity_period": "Reduced movement window confirmed by a second channel (informative silence).",
    "post_surgery_recovery": "Known clinical recovery period — expected, context-explained change.",
    "collar_removed_grooming": "Collar removed for grooming — artefactual gap, not behavioral.",
    "high_noise_exposure": "Yesterday's route crossed a high-noise area — construction near Oak Hill Meadow.",
}

# Contexts emitted even when no dog's primary drift references them
# (the Marlow scenario attaches high_noise_exposure as a second modulator).
EXTRA_CONTEXTS = ["high_noise_exposure"]


def esc(s: str) -> str:
    return s.replace("'", "\\'")


def emit() -> str:
    L: list[str] = []
    w = L.append

    w("// ===========================================================================")
    w("// Barkley DogGraph — synthetic seed data (generated by generate_seed.py)")
    w("// Synthetic data only. No real animals. Not a diagnostic tool.")
    w("// Run AFTER schema.cypher. Safe to re-run (uses MERGE).")
    w("// ===========================================================================")
    w("")

    # ---- Temporal bins (shared) ----
    w("// --- Temporal resolutions (multi-resolution binning) ---")
    for res in ["circadian", "weekly", "quarterly"]:
        w(f"MERGE (:TemporalBin {{id: 'bin_{res}', resolution: '{res}'}});")
    w("")

    # ---- Locations & routes ----
    w("// --- Locations & routes ---")
    for lid, name, lat, ent in LOCATIONS:
        w(f"MERGE (:Location {{id: '{lid}', name: '{esc(name)}', lat: {lat}, location_entropy: {ent}}});")
    for rid, name, terrain, intensity, near in ROUTES:
        w(f"MERGE (:Route {{id: '{rid}', name: '{esc(name)}', terrain: '{terrain}', intensity: {intensity}}});")
    for rid, name, terrain, intensity, near in ROUTES:
        w(f"MATCH (r:Route {{id:'{rid}'}}), (l:Location {{id:'{near}'}}) MERGE (r)-[:LOCATED_NEAR]->(l);")
    w("")

    # ---- Context events (only the ones referenced) ----
    referenced = {d[6] for d in DOGS if d[6]} | set(EXTRA_CONTEXTS)
    w("// --- Context events (missingness / situational taxonomy) ---")
    for i, ctype in enumerate(sorted(referenced)):
        cid = f"ctx_{ctype}"
        desc = CONTEXT_TYPES.get(ctype, ctype)
        w(f"MERGE (:ContextEvent {{id: '{cid}', type: '{ctype}', description: '{esc(desc)}'}});")
    w("")

    # ---- Dogs, baselines, events, drift ----
    for (did, name, breed, byear, drifting, rate, ctx) in DOGS:
        w(f"// ---------- Dog: {name} ----------")
        w(f"MERGE (d:Dog {{id: '{did}'}}) "
          f"SET d.name='{esc(name)}', d.breed='{esc(breed)}', d.birth_year={byear};")
        # Baseline (individual cognitive fingerprint), per-channel mean/scale
        bid = f"base_{did}"
        means = {c: round(rng.uniform(0.35, 0.6), 3) for c in CHANNELS}
        scales = {c: round(rng.uniform(0.08, 0.18), 3) for c in CHANNELS}
        props = ", ".join([f"b.{c}_mean = {means[c]}, b.{c}_scale = {scales[c]}" for c in CHANNELS])
        w(f"MERGE (b:Baseline {{id: '{bid}'}}) "
          f"SET b.established_on='2024-03-01', b.window_days=56, {props};")
        w(f"MATCH (d:Dog {{id:'{did}'}}), (b:Baseline {{id:'{bid}'}}) MERGE (d)-[:HAS_BASELINE]->(b);")

        # A few behavior events across bins (aggregates, not raw millions)
        for j in range(3):
            res = ["circadian", "weekly", "quarterly"][j]
            ch = rng.choice(CHANNELS)
            # value drifts away from baseline mean if the dog is drifting
            drift_push = (rate if drifting else 0.0) * (0.4 + 0.3 * j)
            val = round(min(1.0, max(0.0, means[ch] + drift_push * rng.choice([1, -1]) * 0.5
                                      + rng.uniform(-0.05, 0.05))), 3)
            eid = f"ev_{did}_{j}"
            w(f"MERGE (e:BehaviorEvent {{id: '{eid}'}}) "
              f"SET e.day={120 + j*30}, e.channel='{ch}', e.value={val};")
            w(f"MATCH (d:Dog {{id:'{did}'}}), (e:BehaviorEvent {{id:'{eid}'}}) MERGE (d)-[:GENERATED]->(e);")
            w(f"MATCH (e:BehaviorEvent {{id:'{eid}'}}), (t:TemporalBin {{id:'bin_{res}'}}) "
              f"MERGE (e)-[:FALLS_IN]->(t);")

        # Drift event for drifting dogs, relative to their own baseline
        if drifting and rate >= 0.4:
            drid = f"drift_{did}"
            severity = "high" if rate >= 0.55 else "moderate"
            w(f"MERGE (dr:DriftEvent {{id: '{drid}'}}) "
              f"SET dr.detected_on='2024-09-{10+rng.randint(0,18)}', dr.rate={rate}, "
              f"dr.severity='{severity}', dr.window='quarterly';")
            w(f"MATCH (d:Dog {{id:'{did}'}}), (dr:DriftEvent {{id:'{drid}'}}) MERGE (d)-[:HAS_DRIFT]->(dr);")
            w(f"MATCH (dr:DriftEvent {{id:'{drid}'}}), (b:Baseline {{id:'{bid}'}}) "
              f"MERGE (dr)-[:DRIFTED_FROM]->(b);")
            if ctx:
                w(f"MATCH (dr:DriftEvent {{id:'{drid}'}}), (c:ContextEvent {{id:'ctx_{ctx}'}}) "
                  f"MERGE (dr)-[:MODULATED_BY]->(c);")
        w("")

    # ---- Scenario: yesterday's noise exposure during Marlow's recovery ----
    # Route crossed a high-noise area -> recovery remained incomplete ->
    # compatibility score dropped -> alternative route recommended.
    w("// --- Scenario: yesterday's noise exposure during Marlow's recovery ---")
    w("MATCH (dr:DriftEvent {id:'drift_d_marlow'}), (c:ContextEvent {id:'ctx_high_noise_exposure'}) "
      "MERGE (dr)-[:MODULATED_BY]->(c);")
    w("")

    # ---- Route recommendations (state-aware) ----
    w("// --- Route recommendations (matched to current behavioral state) ---")
    # Kikoo is drifting high -> recommend the calm, flat River Path (low intensity)
    recs = [
        ("d_kikoo",  "r_river", "Low-intensity flat route suits an elevated-drift, lower-activity state."),
        ("d_marlow", "r_quiet", "Quietest route during recovery — avoids the high-noise area crossed yesterday."),
        ("d_sable",  "r_ridge", "High-intensity loop fits a stable, high-energy baseline."),
        ("d_pixel",  "r_ridge", "Stable baseline; can handle hilly terrain."),
    ]
    for did, rid, reason in recs:
        w(f"MATCH (d:Dog {{id:'{did}'}}), (r:Route {{id:'{rid}'}}) "
          f"MERGE (d)-[rr:RECOMMENDED_ROUTE]->(r) SET rr.reason='{esc(reason)}';")
    w("")

    # ---- Social compatibility (PPA-02 social compatibility + Data Value Index) ----
    w("// --- Social compatibility (directed edges with score + reason) ---")
    compat = [
        # a,        b,          score, reason, previous_score (None = stable score)
        ("d_kikoo",  "d_ollie",  0.86, "Complementary arousal profiles; overlapping calm-activity windows.", None),
        ("d_kikoo",  "d_sable",  0.34, "Mismatched intensity; Sable's high drive overwhelms Kikoo's current state.", None),
        ("d_kikoo",  "d_marlow", 0.38, "Score dropped after yesterday's high-noise exposure — Marlow's post-surgery recovery remains incomplete.", 0.72),
        ("d_juno",   "d_sable",  0.78, "Both high-energy, compatible play tempo.", None),
        ("d_pixel",  "d_ollie",  0.71, "Similar low-reactivity social latency.", None),
        ("d_marlow", "d_ollie",  0.69, "Gentle pairing suitable during recovery.", None),
    ]
    for a, b, score, reason, prev in compat:
        prev_prop = f", c.previous_score={prev}" if prev is not None else ""
        w(f"MATCH (a:Dog {{id:'{a}'}}), (b:Dog {{id:'{b}'}}) "
          f"MERGE (a)-[c:COMPATIBLE_WITH]->(b) SET c.score={score}, c.reason='{esc(reason)}'{prev_prop};")
    w("")
    w("// End of synthetic seed.")
    return "\n".join(L) + "\n"


if __name__ == "__main__":
    cypher = emit()
    with open("seed_synthetic.cypher", "w", encoding="utf-8") as f:
        f.write(cypher)
    lines = cypher.count("\n")
    stmts = cypher.count(";")
    print(f"seed_synthetic.cypher written: {lines} lines, {stmts} statements")
